CREATE TABLE products (
    product_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(100),
    ab_name VARCHAR(100),
    fluorophore_id INT,
    host_isotype_name VARCHAR(20),
    part_number VARCHAR(50) UNIQUE,
    clone_name VARCHAR(50),
    product_category VARCHAR(20) CHECK (
        product_category IN ('conjugated_ab', 'purified_ab', 'reagent')
    ),
    top_products BOOLEAN DEFAULT FALSE,

    FOREIGN KEY (fluorophore_id) 
        REFERENCES fluorophores(fluorophore_id)
);
